name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pm-version: [4, 5]
        branch: [stable, php/8.1, php/8.2]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          ref: ${{ matrix.branch }}
          path: build/

      - name: Get repository name
        id: repo-name
        run: echo "value=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PHP version
        id: php-version
        run: echo "value=$(grep -oP '(?<=PHP_VERSION=\").+(?=\")' build/compile.sh | awk -F'.' '{print $1 "." $2}')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: build/
          file: Dockerfile
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.value }}:${{ matrix.pm-version }}-${{ steps.php-version.outputs.value }}
          build-args: |
            COMPILE_SH_ARGS="-f -g -P ${{ matrix.pm-version }}"
