name: Build Docker image

on:
  push:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.php-versions.outputs.value }}

    steps:
      - uses: actions/checkout@v3
      - id: php-versions
        run: echo "value=$(git submodule status | awk '{print "\""$2"\""}' | jq -sc)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.build-matrix.outputs.value) }}

    steps:
      - uses: actions/checkout@v3
      - run: git submodule update ${{ matrix.tag }}

      - name: Get repository name
        id: repo-name
        run: echo "value=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./${{ matrix.tag }}
          file: Dockerfile
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.value }}:${{ matrix.tag }}
